### ISSUE TITLE
Scrimmaging with a team without a submission behaves weirdly

### ISSUE THREAD

**Issue by n8kim1** [battlecode/battlecode21#13]
When a scrimmage is attempted w a team w/o a submission: 
it's created, but it's never queued, and claims either to be "queued" or "error" forever?

We should either give more helpful results (e.g. "error team has no submission"), or prevent the scrimmage from even being created at all (e.g. when the submission is attempted to be queued, check this)

See https://github.com/battlecode/battlehack20/issues/94

**Comment by opheeelia** [comment]
Would it be appropriate if the status was labeled as "failed" to store in the db?

**Comment by n8kim1** [comment]
merged to master!
