### ISSUE TITLE
Display error message field of scrimmages, matches in frontend

### ISSUE THREAD

**Issue by n8kim1** [battlecode/battlecode21#227]
we'll have error messages for these in the backend. just have to show in frontend too (prob thru tooltip)

**Comment by opheeelia** [comment]
should we only show the error message for scrimmages and not submissions or also for submissions?

**Comment by n8kim1** [comment]
both for now? we can change this later
(we shouldn't log sensitive info there ig)

**Comment by opheeelia** [comment]
@n8kim1  where would this be displayed in frontend? it seems like we only display the successful submissions unless i am mistaken

**Comment by n8kim1** [comment]
so i def made a typo; submissions were supposed to be one of the things in the title. issok -- we can do this too
will use diff issue
this one merged to master!
