### ISSUE TITLE
Get back old JDK install instructions

### ISSUE THREAD

**Issue by n8kim1** [battlecode/battlecode21#237]
http://2020.battlecode.org/getting-started
https://github.com/battlecode/battlecode20/blob/master/frontend/src/views/getting-started.js
some rlly nice instructions about how to install Java, basically. removed when we switched to python; we should put this back

(not that it's toooo essential now, but would certainly still help ppl)

**Comment by dash102** [comment]
oo ok will do tmrw!

**Comment by n8kim1** [comment]
done via #243 thanks quinn
