### ISSUE TITLE
Don't rotate tall maps

### ISSUE THREAD

**Issue by j-mao** [battlecode/battlecode21#309]
2e2a639e782117bacb0a1534835a2cd9f422846f needs to be reverted before release. Prefer landscape maps so we don't have to do this at all.

**Comment by gauravarya272** [comment]
Resolved by https://github.com/battlecode/battlecode21/pull/310/commits/891acc4c72b3a3485d72bbd8ced1db650d4011d6 -- I left rotation in as a keyboard toggle for now, just in case, but it's disabled by default
