### ISSUE TITLE
Client displays incorrect equation

### ISSUE THREAD

**Issue by j-mao** [battlecode/battlecode21#313]
The muckraker buff equation was changed from exponential to linear in 3.0.0, but we didn't release a corresponding update in the client UI.

**Comment by gauravarya272** [comment]
Resolved already on the master branch :)

**Comment by j-mao** [comment]
Awesome! Let's cut a release

**Comment by gauravarya272** [comment]
Would be great if frontend could be re-deployed too!

**Comment by j-mao** [comment]
@n8kim1 Can I ask you to do this? I'm unfamiliar with the frontend client deploy process.

**Comment by n8kim1** [comment]
yep will do!
sorry for the delays since I haven't published that script yet -- should rlly finish the last couple lines up
